----------------------------------------------------------------
-- Script Name: SQL4LAB	
-- Developer: Brandon Veasey      
-- Creation Date:09/22/2016	
-- Description: Single Table Queries using the SELECT Command   
----------------------------------------------------------------

-- *************************************************************
-- TAL Distributors – Generate Query Results
-- *************************************************************

-- 1.
SELECT ITEM_NUM, DESCRIPTION, PRICE
FROM BVEASEY.ITEM;

-- 2.
SELECT * FROM BVEASEY.ORDERS
ORDER BY CUSTOMER_NUM;

-- 3.
SELECT CUSTOMER_NAME, CREDIT_LIMIT  
FROM BVEASEY.CUSTOMERS
WHERE CREDIT_LIMIT >= 10000;

-- 4.
SELECT ORDER_NUM, ORDER_DATE  
FROM BVEASEY.ORDERS
WHERE CUSTOMER_NUM = 126 AND ORDER_DATE = '2015-10-15';
	
-- 5.
SELECT CUSTOMER_NUM, CUSTOMER_NAME, REP_NUM
FROM BVEASEY.CUSTOMERS
WHERE REP_NUM = 30 OR REP_NUM = 45;

-- 6.
SELECT ITEM_NUM, DESCRIPTION, CATEGORY
FROM BVEASEY.ITEM
WHERE CATEGORY != 'PZL';

-- 7.
SELECT ITEM_NUM, DESCRIPTION, ON_HAND
FROM BVEASEY.ITEM
WHERE ON_HAND BETWEEN 20 AND 40;

-- 8.
SELECT ITEM_NUM, DESCRIPTION, ON_HAND
FROM BVEASEY.ITEM
WHERE ON_HAND >= 20 AND ON_HAND <= 40;

-- 9.
SELECT ITEM_NUM, CATEGORY, DESCRIPTION, PRICE * ON_HAND
AS ON_HAND_TOY_VALUE 
FROM BVEASEY.ITEM
WHERE CATEGORY = 'TOY' 


-- 10.
SELECT ITEM_NUM, DESCRIPTION, PRICE * ON_HAND
AS ON_HAND_GT1500_VALUE 
FROM BVEASEY.ITEM
WHERE ( PRICE * ON_HAND) >= 1500; 

-- 11.
SELECT ITEM_NUM, CATEGORY, DESCRIPTION
FROM BVEASEY.ITEM
WHERE CATEGORY IN ( 'GME', 'PZL' );

-- 12.
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM BVEASEY.CUSTOMERS
WHERE CUSTOMER_NAME LIKE 'C%';

-- 13.
SELECT * FROM BVEASEY.ITEM
ORDER BY DESCRIPTION;

-- 14.
SELECT * FROM BVEASEY.ITEM
ORDER BY STOREHOUSE, ITEM_NUM;


-- 15.
SELECT * FROM BVEASEY.CUSTOMERS
WHERE CREDIT_LIMIT IS NULL;

-- 16.
SELECT COUNT(BALANCE) 
AS BAL_BIGGER_LIMIT 
FROM BVEASEY.CUSTOMERS
WHERE BALANCE > CREDIT_LIMIT;

-- 17.
SELECT CUSTOMER_NUM, CREDIT_LIMIT, REP_NUM, SUM(BALANCE)
AS SUM_BAL
FROM BVEASEY.CUSTOMERS
WHERE REP_NUM = 15 AND BALANCE < CREDIT_LIMIT
GROUP BY CUSTOMER_NUM, CREDIT_LIMIT, REP_NUM

-- 18.
SELECT ITEM_NUM, DESCRIPTION, ON_HAND
FROM BVEASEY.ITEM
WHERE ON_HAND > 
	(SELECT AVG(ON_HAND)
	FROM BVEASEY.ITEM);

--19.
SELECT ITEM_NUM, DESCRIPTION, PRICE
FROM BVEASEY.ITEM
WHERE PRICE =
	(SELECT MIN(PRICE)
	FROM BVEASEY.ITEM);

-- 20.
SELECT REP_NUM, SUM(BALANCE)
AS SUM_OF_BAL 
FROM BVEASEY.CUSTOMERS
GROUP BY REP_NUM
ORDER BY REP_NUM;

-- 21.
SELECT REP_NUM, SUM(BALANCE)
AS SUM_OF_BIG_BAL 
FROM BVEASEY.CUSTOMERS
GROUP BY REP_NUM
HAVING SUM(BALANCE) > 5000
ORDER BY REP_NUM;

-- 22.
SELECT * FROM BVEASEY.REP
WHERE RATE IS NOT NULL;

-- 23.
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM BVEASEY.CUSTOMERS
WHERE CUSTOMER_NAME LIKE '%TOY%';

-- *************************************************************
-- Colonial Adventure Tours – Generate Query Results
-- *************************************************************

-- 24.
SELECT LAST_NAME, STATE
FROM BVEASEY.GUIDE
WHERE STATE <> 'MA';

-- 25.
SELECT TRIP_NAME, TYPE
FROM BVEASEY.TRIP
WHERE TYPE = 'BIKING';

-- 26.
SELECT TRIP_NAME, SEASON
FROM BVEASEY.TRIP
WHERE SEASON = 'SUMMER';

-- 27.
SELECT TRIP_NAME, TYPE, DISTANCE
FROM BVEASEY.TRIP
WHERE TYPE = 'HIKING' AND DISTANCE > 10;

-- 28.
SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME, STATE
FROM BVEASEY.CUSTOMER
WHERE STATE IN ('NJ', 'NY', 'PA');

-- 29.
SELECT CUSTOMER_NUM, LAST_NAME, FIRST_NAME, STATE
FROM BVEASEY.CUSTOMER
WHERE STATE IN ('NJ', 'NY', 'PA')
order by state desc, LAST_NAME;

-- 30.
SELECT COUNT(STATE) 
AS NUM_ME_MA_TRIPS  
FROM BVEASEY.TRIP
WHERE STATE in ('ME', 'MA');

-- 31.
SELECT  STATE, COUNT(STATE) 
AS NUM_TRIPS
FROM BVEASEY.TRIP
group by STATE
order by STATE

-- 32.
SELECT COUNT(TRIP_ID)
AS NUM_20_75_TRIPS
FROM BVEASEY.RESERVATION
where TRIP_PRICE > 20 and TRIP_PRICE < 75;

-- 33.
SELECT * FROM BVEASEY.RESERVATION
where NUM_PERSONS is null;

-- 34.
SELECT TYPE, count(TYPE)
AS NUM_TYPE_TRIPS
FROM BVEASEY.TRIP
group by TYPE;

-- 35.
SELECT RESERVATION_ID, TRIP_ID, CUSTOMER_NUM, NUM_PERSONS, (TRIP_PRICE + OTHER_FEES) * NUM_PERSONS
AS TOTAL_TRIP_PRICE 
FROM BVEASEY.RESERVATION
where NUM_PERSONS > 4;

-- 36.
SELECT TRIP_NAME, STATE
FROM BVEASEY.TRIP
WHERE TRIP_NAME LIKE '%Pond%';

-- 37.
SELECT LAST_NAME, FIRST_NAME, HIRE_DATE
FROM BVEASEY.GUIDE
where HIRE_DATE < '2013-06-10';

-- 38.
SELECT TYPE, avg(DISTANCE) as AVG_DISTANCE, avg(MAX_GRP_SIZE) as AVG_SIZE
FROM BVEASEY.TRIP
group by TYPE
order by TYPE;

-- 39.
SELECT distinct(SEASON)
FROM BVEASEY.TRIP;

-- 40.
SELECT * FROM BVEASEY.GUIDE
where PHONE_NUM is not null;

-- 41.
SELECT TRIP_ID, TRIP_NAME
FROM BVEASEY.TRIP
where TRIP_NAME like '%MT%';
